### ISSUE TITLE
И как это понимать.

### ISSUE THREAD

**Issue by internetrvze** [vuchaev2015/hmn-simple-reger#5]
![image](https://github.com/vuchaev2015/hmn-simple-reger/assets/65215768/dc983fab-51ef-423f-8843-01ad4743035f)

**Comment by vuchaev2015** [comment]
Попробуйте теперь запустить

**Comment by internetrvze** [comment]
Всё, теперь работает, благодарю
![image](https://github.com/vuchaev2015/hmn-simple-reger/assets/65215768/14a402e9-d107-4902-a14c-dd11b557d654)
